### ISSUE TITLE
Error: Configuration file not found. Either pass --config, or create folio.config.(js|ts) file

### ISSUE THREAD

**Issue by avevlad** [microsoft/playwright-test#243] opened 2021-04-14 18:39 UTC
Why need create configuration file?

```
"dependencies": {
    "@playwright/test": "^0.1101.0"
  },
```

run: `npx folio --tag=chromium`

```
Error: Configuration file not found. Either pass --config, or create folio.config.(js|ts) file
    at runTests (/Users/name/projects/playwright-test/examples/basic-ts/node_modules/folio/out/cli.js:116:15)
    at Command.<anonymous> (/Users/name/projects/playwright-test/examples/basic-ts/node_modules/folio/out/cli.js:87:15)
    at Command.listener [as _actionHandler] (/Users/name/projects/playwright-test/examples/basic-ts/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/Users/name/projects/playwright-test/examples/basic-ts/node_modules/commander/index.js:1002:14)
    at Command.parse (/Users/name/projects/playwright-test/examples/basic-ts/node_modules/commander/index.js:801:10)
    at Object.<anonymous> (/Users/name/projects/playwright-test/examples/basic-ts/node_modules/folio/out/cli.js:94:13)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/name/projects/playwright-test/examples/basic-ts/node_modules/folio/cli.js:19:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)```

**Comment by BillyBolton** [comment] 2021-04-15 02:02
This requirement is needed in the most recent version of Playwright-Test and Folio. They developers make each test environment flexible to their needs, while consistent. Writing a config.ts file is easy. [Have you checked out the documentation  for writing a configuration file yet?](https://github.com/microsoft/playwright-test#write-a-configuration-file) [There's more information about how flexible config files can be here too.](https://github.com/microsoft/folio#writing-a-configuration-file)  

When you write one, put it in the root of your directory and it should work. Give it a try and if you have problems, post back. :)

**Comment by mxschmitt** [comment] 2021-06-09 10:38
Closing since the [new test-runner](https://playwright.dev/docs/test-intro) is quite different. If its still reproducible for you, please create a new issue.

**Closed by mxschmitt** 2021-06-09 10:38 UTC
