### ISSUE TITLE
Support for specific Browser flavour

### ISSUE THREAD

**Issue by DieTapete** [microsoft/playwright-test#259] opened 2021-05-03 09:27 UTC
Is there a way to install playwright-test with just a specific browser type like chromium similar to `playwright-chromium`? As far as I can tell the dependency in `package.json` downloads the whole package.

**Comment by mxschmitt** [comment] 2021-05-03 09:33
Seems like a duplicate of #11

**Closed by mxschmitt** 2021-05-03 09:33 UTC
