### ISSUE TITLE
browser.newContext: options.isMobile is not supported in Firefox

### ISSUE THREAD

**Issue by burritoIand** [microsoft/playwright-test#262] opened 2021-05-19 19:58 UTC
When I tried to run a test with mobile emulation, I see the error in the title.

ran test with `npx folio`

```
const assert = require('assert');
const { devices } = require('playwright');
const { folio } = require('@playwright/test');

const fixtures = folio.extend();

fixtures.contextOptions.override(async ({ contextOptions }, runTest) => {
  await runTest({
    ...contextOptions,
    ...devices['iPhone SE'],
  });
});

const { describe, it } = fixtures.build();

...
```

Separate, how could I tell it to run against e.g. an array of mobile devices as opposed to a single one?

**Comment by mxschmitt** [comment] 2021-06-09 10:28
Closing as part of the triage process since the [new test-runner](https://playwright.dev/docs/test-intro) got released yesterday. Please create a new issue if its still reproducible.

**Closed by mxschmitt** 2021-06-09 10:28 UTC
