### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright-test#33] opened 2020-04-27 15:14 UTC
It would be nice to have a watch mode that automatically re-runs tests when the file is saved similar to cypress. #6

- Allow the user to keep the browser open and close it when the file is re-run
- After hook to allow cleanup (ideally the same ones in #8 #9)

**Comment by JoelEinbinder** [comment] 2020-04-28 02:53
This should mostly work out of the box today!

Keeping the browser open requires global cleanup for Jest runners. I filed it as https://github.com/facebook/jest/issues/9795 and they seem open to it.

**Comment by jperl** [comment] 2020-04-28 03:04
It's a total hack but we implemented this behavior in qawolf by creating a Jest [watch plugin](https://github.com/qawolf/qawolf/blob/master/src/watch/WatchPlugin.ts). We use `shouldRunTestSuite` to send a command via a tcp server to the test to close the browser. I would love to get rid of this and swap it out for `playwright-runner`.

**Comment by laurentpayot** [comment] 2020-11-13 14:26
I use the following npm scripts to implement this behaviour with [chokidar-cli](https://github.com/kimmobrunfeldt/chokidar-cli):
```json
"test:e2e": "cd tests/e2e && folio --workers `grep -c ^processor /proc/cpuinfo` --param screenshotOnFailure",
"test:e2e:watch": "npm run test:e2e ; cd tests/e2e && chokidar './**/*.ts' -c 'echo \"\n{path} was modified\n\" && cd ../.. && npm run test:e2e -- --test-match \"{path}\"'",
```
but it is nothing compared to the watch options Jest spoils us with.

@mxschmitt don't you think this issue should be re-opened?

**Comment by mxschmitt** [comment] 2020-11-13 14:28
yeah lets open I guess.

**Comment by mxschmitt** [comment] 2021-06-09 10:01
Closing as duplicate of https://github.com/microsoft/folio/issues/150 we track it there.

**Closed by mxschmitt** 2021-06-09 10:01 UTC
Labels: P3-collecting-feedback
